name: Deploy CMS
on:
  repository_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - run: npm run export
      - uses: actions/checkout@master
      - uses: peaceiris/actions-gh-pages@v3
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          publish_dir: ./dist
